#!/usr/bin/env bash

git checkout gh-pages
git merge master --no-edit
npm run build
git add ./dists/
git commit -m "update dist for deploy"
git subtree push --prefix dist origin gh-pages
git checkout master